# -*- coding: utf-8 -*-
"""Computer Security(full project).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JCltTvBqdhkCjd_60oHighXSgIg4bIze
"""

# ============================================
# PHISHSHIELD AI
# Multimodal Phishing Website Detection
# ============================================

PROJECT_NAME = "PhishShield AI"

print("Project:", PROJECT_NAME)
print("Environment: Google Colab")
print("Status: Initializing...")

!pip -q install ucimlrepo pandas numpy scikit-learn matplotlib seaborn tensorflow

"""#Importing Required Libraries :)"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from ucimlrepo import fetch_ucirepo

print("All libraries imported successfully.")

"""#Downloading the PhiUSIIL Phishing URL Dataset :)"""

# Fetch PhiUSIIL dataset from UCI Repository
dataset = fetch_ucirepo(id=967)

print("Dataset downloaded successfully.")

"""#Separating Features and Target..."""

# Separate input features and target label
X = dataset.data.features
y = dataset.data.targets

print("Features shape:", X.shape)
print("Target shape:", y.shape)

"""#Displaying First Few Rows of the Dataset..."""

print("First 5 rows of the features:")
display(X.head())

print("\nFirst 5 rows of the target:")
display(y.head())

"""#Displaying All Feature Names"""

print("Total number of features:", len(X.columns))
print("\nFeature names:\n")

for i, column in enumerate(X.columns, start=1):
    print(f"{i}. {column}")

"""#Checking the Dataset Size"""

print("Number of samples:", X.shape[0])
print("Number of features:", X.shape[1])
print("Target shape:", y.shape)

"""#Checking Target/Class Distribution..."""

print("Class distribution:")
print(y.value_counts())

"""#Visualizing Class Distribution..."""

plt.figure(figsize=(7, 5))

sns.countplot(
    x=y.iloc[:, 0]
)

plt.title("Phishing vs Legitimate Class Distribution")
plt.xlabel("Class")
plt.ylabel("Number of Samples")
plt.show()

"""#Checking Missing Values :)"""

print("Missing values in each feature:\n")

missing_values = X.isnull().sum()

display(
    missing_values[missing_values > 0]
)

"""#Checking Duplicate Rows"""

duplicate_count = X.duplicated().sum()

print("Number of duplicate feature rows:", duplicate_count)

"""#Generating Dataset Summary..."""

print("=" * 50)
print("PHIUSIIL DATASET SUMMARY")
print("=" * 50)

print("Total Samples :", X.shape[0])
print("Total Features:", X.shape[1])
print("Missing Values:", X.isnull().sum().sum())
print("Duplicate Rows:", X.duplicated().sum())

print("\nClass Distribution:")
print(y.value_counts())

print("=" * 50)

"""# **DATASET PREPARATION**

#Inspecting All Dataset Columns and Data Types..
"""

# ============================================
# BLOCK 13 — Inspect Columns and Data Types
# ============================================

print("=" * 70)
print("DATASET COLUMN INFORMATION")
print("=" * 70)

column_info = pd.DataFrame({
    "Column": X.columns,
    "Data Type": X.dtypes.astype(str),
    "Unique Values": [X[col].nunique() for col in X.columns]
})

display(column_info)

print("\nTotal Columns:", len(column_info))

"""#Identifying the URL Column"""

# ============================================
# BLOCK 14 — Identify URL-Related Columns
# ============================================

url_columns = [
    col for col in X.columns
    if any(keyword in col.lower()
           for keyword in ["url", "domain", "address", "link"])
]

print("Possible URL-related columns:")
print()

for col in url_columns:
    print("•", col)

"""#Displaying Sample URLs"""

for col in url_columns:
    print("\n" + "=" * 70)
    print("COLUMN:", col)
    print("=" * 70)

    display(X[[col]].head(10))

"""#Checking the Target Label Mapping"""

print("=" * 60)
print("TARGET LABEL MAPPING")
print("=" * 60)

print("""
Based on the PhiUSIIL dataset documentation:

0 = Phishing
1 = Legitimate
""")

print("Actual class counts:")
display(y.value_counts().sort_index())

"""#Creating a Clean Label Column"""

y_clean = y.iloc[:, 0].astype(int).copy()

print("Target variable:")
print(y_clean.head())

print("\nUnique labels:")
print(sorted(y_clean.unique()))

"""#Creating a Complete Working Dataset......."""

data = X.copy()

# Add target label
data["label"] = y_clean

print("Working dataset shape:", data.shape)

display(data.head())

"""#Checking the URL Column Content.."""

# Automatically find the main URL column
url_col_candidates = [
    col for col in data.columns
    if "url" in col.lower()
]

print("URL-related columns:")
print(url_col_candidates)

"""#Showing Real Phishing and Legitimate URLs"""

# Change this automatically after identifying the URL column
url_column = url_col_candidates[0]

print("Selected URL column:", url_column)

print("\n--- LEGITIMATE URL EXAMPLES ---")
display(
    data[data["label"] == 1][[url_column, "label"]].head(10)
)

print("\n--- PHISHING URL EXAMPLES ---")
display(
    data[data["label"] == 0][[url_column, "label"]].head(10)
)

"""#URL-BASED NEURAL NETWORK"""

url_data = data[[url_column, "label"]].copy()

# Rename columns for simplicity
url_data.columns = ["url", "label"]

# Remove any missing URL values
url_data = url_data.dropna(subset=["url"])

# Convert URL to string
url_data["url"] = url_data["url"].astype(str)

print("=" * 60)
print("URL DATASET")
print("=" * 60)

print("Total samples:", len(url_data))
print("Total columns:", url_data.shape[1])

display(url_data.head())

"""#Check URL Length Distribution"""

url_data["url_length"] = url_data["url"].apply(len)

print("Minimum URL length:", url_data["url_length"].min())
print("Maximum URL length:", url_data["url_length"].max())
print("Average URL length:", round(url_data["url_length"].mean(), 2))
print("Median URL length:", url_data["url_length"].median())

"""#Visualizing URL Length Distribution"""

plt.figure(figsize=(10, 5))

plt.hist(
    url_data["url_length"],
    bins=100
)

plt.title("Distribution of URL Lengths")
plt.xlabel("URL Length")
plt.ylabel("Number of URLs")

plt.show()

"""#Compare URL Length by Class"""

plt.figure(figsize=(8, 5))

sns.boxplot(
    data=url_data,
    x="label",
    y="url_length"
)

plt.title("URL Length Comparison")
plt.xlabel("Label (0 = Phishing, 1 = Legitimate)")
plt.ylabel("URL Length")

plt.show()

"""#Remove the Temporary URL-Length Column"""

url_data = url_data.drop(columns=["url_length"])

print("Final URL dataset shape:", url_data.shape)
display(url_data.head())

"""#Shuffling the Dataset"""

url_data = url_data.sample(
    frac=1,
    random_state=42
).reset_index(drop=True)

print("Dataset shuffled successfully.")
display(url_data.head())

"""#Preparing URL Text and Labels"""

urls = url_data["url"].values
labels = url_data["label"].values

print("Number of URLs:", len(urls))
print("Number of labels:", len(labels))

print("\nExample URL:")
print(urls[0])

print("\nExample label:")
print(labels[0])

"""#Checking Final Class Distribution"""

unique_labels, label_counts = np.unique(
    labels,
    return_counts=True
)

print("=" * 60)
print("FINAL URL CLASS DISTRIBUTION")
print("=" * 60)

for label, count in zip(unique_labels, label_counts):
    class_name = "Phishing" if label == 0 else "Legitimate"
    print(f"{label} = {class_name}: {count}")

"""#PHASE 2 — URL-BASED NEURAL NETWORK

#Importing Train/Test Split
"""

from sklearn.model_selection import train_test_split

print("Train/test split module imported successfully.")

"""#Creating Training, Validation and Test Sets"""

# ============================================
# BLOCK 30 — Create Train / Validation / Test Sets
# ============================================

# First: 80% training, 20% temporary
X_train, X_temp, y_train, y_temp = train_test_split(
    urls,
    labels,
    test_size=0.20,
    stratify=labels,
    random_state=42
)

# Second: split the temporary 20% into
# 10% validation and 10% test
X_val, X_test, y_val, y_test = train_test_split(
    X_temp,
    y_temp,
    test_size=0.50,
    stratify=y_temp,
    random_state=42
)

print("=" * 60)
print("DATASET SPLIT")
print("=" * 60)

print("Training samples  :", len(X_train))
print("Validation samples:", len(X_val))
print("Test samples      :", len(X_test))

"""#Verify Class Distribution After Split"""

print("TRAINING SET")
print(pd.Series(y_train).value_counts().sort_index())

print("\nVALIDATION SET")
print(pd.Series(y_val).value_counts().sort_index())

print("\nTEST SET")
print(pd.Series(y_test).value_counts().sort_index())

"""#Display Split Percentages"""

total = len(urls)

print("=" * 60)
print("DATASET SPLIT PERCENTAGES")
print("=" * 60)

print(f"Training   : {len(X_train):,} ({len(X_train)/total*100:.1f}%)")
print(f"Validation : {len(X_val):,} ({len(X_val)/total*100:.1f}%)")
print(f"Testing    : {len(X_test):,} ({len(X_test)/total*100:.1f}%)")

"""#Show Examples From Each Split"""

print("TRAINING EXAMPLE:")
print(X_train[0])
print("Label:", y_train[0])

print("\nVALIDATION EXAMPLE:")
print(X_val[0])
print("Label:", y_val[0])

print("\nTEST EXAMPLE:")
print(X_test[0])
print("Label:", y_test[0])

"""#Verify No Overlap Between Splits"""

train_set = set(X_train)
val_set = set(X_val)
test_set = set(X_test)

train_val_overlap = len(train_set.intersection(val_set))
train_test_overlap = len(train_set.intersection(test_set))
val_test_overlap = len(val_set.intersection(test_set))

print("=" * 60)
print("DATA LEAKAGE CHECK")
print("=" * 60)

print("Train ∩ Validation:", train_val_overlap)
print("Train ∩ Test      :", train_test_overlap)
print("Validation ∩ Test :", val_test_overlap)

"""#Final Dataset Split Summary"""

print("=" * 70)
print("PHISHSHIELD AI — URL DATASET SPLIT SUMMARY")
print("=" * 70)

print(f"Total URLs       : {len(urls):,}")
print(f"Training URLs    : {len(X_train):,}")
print(f"Validation URLs  : {len(X_val):,}")
print(f"Testing URLs     : {len(X_test):,}")

print("\nSplit Ratio: 80% Training / 10% Validation / 10% Testing")

print("\nData leakage check:")
print(f"Train-Val overlap: {train_val_overlap}")
print(f"Train-Test overlap: {train_test_overlap}")
print(f"Val-Test overlap: {val_test_overlap}")

print("=" * 70)

"""#URL-BASED NEURAL NETWORK

#Importing TensorFlow and Keras
"""

import tensorflow as tf

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

print("TensorFlow version:", tf.__version__)
print("TensorFlow/Keras imported successfully.")

"""#Define Character-Level Tokenizer"""

tokenizer = Tokenizer(
    char_level=True,
    lower=False,
    filters=""
)

# IMPORTANT:
# Fit ONLY on training URLs to avoid information leakage.
tokenizer.fit_on_texts(X_train)

print("Character vocabulary size:", len(tokenizer.word_index))

print("\nFirst 30 characters in vocabulary:")

for char, index in list(tokenizer.word_index.items())[:30]:
    print(repr(char), "->", index)

"""#Convert URLs Into Character Sequences"""

X_train_seq = tokenizer.texts_to_sequences(X_train)
X_val_seq = tokenizer.texts_to_sequences(X_val)
X_test_seq = tokenizer.texts_to_sequences(X_test)

print("Example original URL:")
print(X_train[0])

print("\nConverted sequence:")
print(X_train_seq[0])

"""#Analyze Sequence Lengths"""

train_lengths = np.array([
    len(sequence)
    for sequence in X_train_seq
])

print("=" * 60)
print("URL SEQUENCE LENGTH ANALYSIS")
print("=" * 60)

print("Minimum length :", train_lengths.min())
print("Maximum length :", train_lengths.max())
print("Mean length    :", round(train_lengths.mean(), 2))
print("Median length  :", np.median(train_lengths))

print("\nPercentiles:")
print("90th percentile :", np.percentile(train_lengths, 90))
print("95th percentile :", np.percentile(train_lengths, 95))
print("99th percentile :", np.percentile(train_lengths, 99))

"""#Select Maximum Sequence Length"""

# We use the 95th percentile as a practical sequence length.
# This reduces excessive padding while keeping most URL information.

MAX_LENGTH = int(np.percentile(train_lengths, 95))

# Put a reasonable upper limit for computational efficiency
MAX_LENGTH = min(MAX_LENGTH, 300)

print("Selected MAX_LENGTH:", MAX_LENGTH)

"""#Pad Training, Validation and Test Sequences"""

# ============================================
# BLOCK 41 — Pad URL Sequences
# ============================================

X_train_pad = pad_sequences(
    X_train_seq,
    maxlen=MAX_LENGTH,
    padding="post",
    truncating="post"
)

X_val_pad = pad_sequences(
    X_val_seq,
    maxlen=MAX_LENGTH,
    padding="post",
    truncating="post"
)

X_test_pad = pad_sequences(
    X_test_seq,
    maxlen=MAX_LENGTH,
    padding="post",
    truncating="post"
)

print("Training shape   :", X_train_pad.shape)
print("Validation shape :", X_val_pad.shape)
print("Testing shape    :", X_test_pad.shape)

"""#Check the Padded URL Representation"""

print("Original URL:")
print(X_train[0])

print("\nTokenized sequence:")
print(X_train_seq[0])

print("\nPadded sequence:")
print(X_train_pad[0])

print("\nFinal sequence length:")
print(len(X_train_pad[0]))

"""#Convert Labels to NumPy Arrays"""

y_train_nn = np.array(y_train).astype("float32")
y_val_nn = np.array(y_val).astype("float32")
y_test_nn = np.array(y_test).astype("float32")

print("Training labels shape   :", y_train_nn.shape)
print("Validation labels shape :", y_val_nn.shape)
print("Testing labels shape    :", y_test_nn.shape)

print("\nUnique labels:", np.unique(y_train_nn))

"""#Final URL Neural Network Input Summary"""

VOCAB_SIZE = len(tokenizer.word_index) + 1

print("=" * 70)
print("URL NEURAL NETWORK INPUT SUMMARY")
print("=" * 70)

print("Training samples :", X_train_pad.shape[0])
print("Validation samples:", X_val_pad.shape[0])
print("Test samples     :", X_test_pad.shape[0])

print("\nVocabulary size  :", VOCAB_SIZE)
print("Maximum sequence length:", MAX_LENGTH)

print("\nInput shape:", X_train_pad.shape[1:])

print("=" * 70)

"""#Importing CNN Layers"""

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import (
    Embedding,
    Conv1D,
    GlobalMaxPooling1D,
    Dense,
    Dropout,
    BatchNormalization
)

print("CNN layers imported successfully.")

"""#Build Character-Level CNN Model"""

cnn_model = Sequential([

    # Character embedding
    Embedding(
        input_dim=VOCAB_SIZE,
        output_dim=64,
        input_length=MAX_LENGTH
    ),

    # First convolution layer
    Conv1D(
        filters=128,
        kernel_size=5,
        activation="relu",
        padding="same"
    ),

    BatchNormalization(),

    # Second convolution layer
    Conv1D(
        filters=128,
        kernel_size=3,
        activation="relu",
        padding="same"
    ),

    # Convert sequence into fixed-size representation
    GlobalMaxPooling1D(),

    # Fully connected layer
    Dense(
        128,
        activation="relu"
    ),

    Dropout(0.40),

    # Binary classification output
    Dense(
        1,
        activation="sigmoid"
    )
])

print("Character-Level CNN created successfully.")

"""#Display CNN Architecture"""

cnn_model.summary()

"""#Compile the CNN Model"""

cnn_model.compile(
    optimizer=tf.keras.optimizers.Adam(
        learning_rate=0.001
    ),

    loss="binary_crossentropy",

    metrics=[
        "accuracy",
        tf.keras.metrics.Precision(name="precision"),
        tf.keras.metrics.Recall(name="recall")
    ]
)

print("CNN model compiled successfully.")

"""#Define Training Callbacks"""

from tensorflow.keras.callbacks import (
    EarlyStopping,
    ReduceLROnPlateau,
    ModelCheckpoint
)

early_stopping = EarlyStopping(
    monitor="val_loss",
    patience=3,
    restore_best_weights=True,
    verbose=1
)

reduce_lr = ReduceLROnPlateau(
    monitor="val_loss",
    factor=0.5,
    patience=1,
    min_lr=1e-6,
    verbose=1
)

checkpoint = ModelCheckpoint(
    "best_url_cnn.keras",
    monitor="val_loss",
    save_best_only=True,
    verbose=1
)

print("Training callbacks created successfully.")

"""# Train the Character-Level CNN"""

history_cnn = cnn_model.fit(
    X_train_pad,
    y_train_nn,

    validation_data=(
        X_val_pad,
        y_val_nn
    ),

    epochs=15,
    batch_size=256,

    callbacks=[
        early_stopping,
        reduce_lr,
        checkpoint
    ],

    verbose=1
)

"""#Evaluate CNN on Test Set"""

cnn_results = cnn_model.evaluate(
    X_test_pad,
    y_test_nn,
    verbose=1
)

print("\n" + "=" * 60)
print("CNN TEST RESULTS")
print("=" * 60)

for metric_name, metric_value in zip(
    cnn_model.metrics_names,
    cnn_results
):
    print(f"{metric_name}: {metric_value:.4f}")

"""#Plot CNN Training Accuracy"""

plt.figure(figsize=(10, 5))

plt.plot(
    history_cnn.history["accuracy"],
    label="Training Accuracy"
)

plt.plot(
    history_cnn.history["val_accuracy"],
    label="Validation Accuracy"
)

plt.title("Character-Level CNN Accuracy")
plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.legend()
plt.grid(True)

plt.show()

"""#Plot CNN Loss"""

plt.figure(figsize=(10, 5))

plt.plot(
    history_cnn.history["loss"],
    label="Training Loss"
)

plt.plot(
    history_cnn.history["val_loss"],
    label="Validation Loss"
)

plt.title("Character-Level CNN Loss")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.legend()
plt.grid(True)

plt.show()

"""#Generate CNN Predictions"""

cnn_probabilities = cnn_model.predict(
    X_test_pad,
    batch_size=512,
    verbose=1
).ravel()

# Probability >= 0.5 → Legitimate (1)
# Probability < 0.5 → Phishing (0)

cnn_predictions = (
    cnn_probabilities >= 0.5
).astype(int)

print("Predictions generated successfully.")

print("\nFirst 10 predicted probabilities:")
print(cnn_probabilities[:10])

print("\nFirst 10 predictions:")
print(cnn_predictions[:10])

print("\nFirst 10 actual labels:")
print(y_test_nn[:10].astype(int))

"""#Detailed CNN Classification Report"""

from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

cnn_accuracy = accuracy_score(
    y_test_nn,
    cnn_predictions
)

cnn_precision = precision_score(
    y_test_nn,
    cnn_predictions
)

cnn_recall = recall_score(
    y_test_nn,
    cnn_predictions
)

cnn_f1 = f1_score(
    y_test_nn,
    cnn_predictions
)

cnn_auc = roc_auc_score(
    y_test_nn,
    cnn_probabilities
)

print("=" * 70)
print("CHARACTER-LEVEL CNN — DETAILED EVALUATION")
print("=" * 70)

print(f"Accuracy  : {cnn_accuracy:.4f}")
print(f"Precision : {cnn_precision:.4f}")
print(f"Recall    : {cnn_recall:.4f}")
print(f"F1 Score  : {cnn_f1:.4f}")
print(f"ROC-AUC   : {cnn_auc:.4f}")

print("\nClassification Report:")
print(
    classification_report(
        y_test_nn,
        cnn_predictions,
        target_names=[
            "Phishing",
            "Legitimate"
        ]
    )
)

"""#CNN Confusion Matrix"""

cm_cnn = confusion_matrix(
    y_test_nn,
    cnn_predictions
)

plt.figure(figsize=(7, 6))

sns.heatmap(
    cm_cnn,
    annot=True,
    fmt="d",
    cmap="Blues",
    xticklabels=[
        "Phishing",
        "Legitimate"
    ],
    yticklabels=[
        "Phishing",
        "Legitimate"
    ]
)

plt.title("Character-Level CNN Confusion Matrix")
plt.xlabel("Predicted Label")
plt.ylabel("Actual Label")

plt.show()

"""#Save the First URL Model"""

cnn_model.save(
    "phishshield_url_cnn.keras"
)

print("CNN model saved as:")
print("phishshield_url_cnn.keras")

"""#Import BiLSTM Layers"""

from tensorflow.keras.layers import LSTM, Bidirectional

print("BiLSTM layers imported successfully.")

"""#Build Character-Level BiLSTM Model"""

bilstm_model = Sequential([

    # Character embedding
    Embedding(
        input_dim=VOCAB_SIZE,
        output_dim=64,
        input_length=MAX_LENGTH
    ),

    # Bidirectional LSTM
    Bidirectional(
        LSTM(
            64,
            return_sequences=True
        )
    ),

    Dropout(0.30),

    # Second BiLSTM layer
    Bidirectional(
        LSTM(
            32
        )
    ),

    # Fully connected layer
    Dense(
        64,
        activation="relu"
    ),

    Dropout(0.40),

    # Binary classification
    Dense(
        1,
        activation="sigmoid"
    )
])

print("Character-Level BiLSTM created successfully.")

"""#Display BiLSTM Architecture"""

bilstm_model.summary()

"""#Compile BiLSTM Model"""

bilstm_model.compile(
    optimizer=tf.keras.optimizers.Adam(
        learning_rate=0.001
    ),

    loss="binary_crossentropy",

    metrics=[
        "accuracy",
        tf.keras.metrics.Precision(name="precision"),
        tf.keras.metrics.Recall(name="recall")
    ]
)

print("BiLSTM model compiled successfully.")

"""#Define BiLSTM Training Callbacks"""

early_stopping_bilstm = EarlyStopping(
    monitor="val_loss",
    patience=3,
    restore_best_weights=True,
    verbose=1
)

reduce_lr_bilstm = ReduceLROnPlateau(
    monitor="val_loss",
    factor=0.5,
    patience=1,
    min_lr=1e-6,
    verbose=1
)

checkpoint_bilstm = ModelCheckpoint(
    "best_url_bilstm.keras",
    monitor="val_loss",
    save_best_only=True,
    verbose=1
)

print("BiLSTM callbacks created successfully.")

"""#Train Character-Level BiLSTM"""

history_bilstm = bilstm_model.fit(
    X_train_pad,
    y_train_nn,

    validation_data=(
        X_val_pad,
        y_val_nn
    ),

    epochs=15,
    batch_size=256,

    callbacks=[
        early_stopping_bilstm,
        reduce_lr_bilstm,
        checkpoint_bilstm
    ],

    verbose=1
)

"""#Evaluate BiLSTM on Test Set"""

bilstm_results = bilstm_model.evaluate(
    X_test_pad,
    y_test_nn,
    verbose=1
)

print("\n" + "=" * 60)
print("BiLSTM TEST RESULTS")
print("=" * 60)

for metric_name, metric_value in zip(
    bilstm_model.metrics_names,
    bilstm_results
):
    print(f"{metric_name}: {metric_value:.4f}")

"""#Generate BiLSTM Predictions"""

bilstm_probabilities = bilstm_model.predict(
    X_test_pad,
    batch_size=512,
    verbose=1
).ravel()

bilstm_predictions = (
    bilstm_probabilities >= 0.5
).astype(int)

print("BiLSTM predictions generated successfully.")

"""#Detailed BiLSTM Evaluation"""

bilstm_accuracy = accuracy_score(
    y_test_nn,
    bilstm_predictions
)

bilstm_precision = precision_score(
    y_test_nn,
    bilstm_predictions
)

bilstm_recall = recall_score(
    y_test_nn,
    bilstm_predictions
)

bilstm_f1 = f1_score(
    y_test_nn,
    bilstm_predictions
)

bilstm_auc = roc_auc_score(
    y_test_nn,
    bilstm_probabilities
)

print("=" * 70)
print("CHARACTER-LEVEL BiLSTM — DETAILED EVALUATION")
print("=" * 70)

print(f"Accuracy  : {bilstm_accuracy:.4f}")
print(f"Precision : {bilstm_precision:.4f}")
print(f"Recall    : {bilstm_recall:.4f}")
print(f"F1 Score  : {bilstm_f1:.4f}")
print(f"ROC-AUC   : {bilstm_auc:.4f}")

print("\nClassification Report:")

print(
    classification_report(
        y_test_nn,
        bilstm_predictions,
        target_names=[
            "Phishing",
            "Legitimate"
        ]
    )
)

"""#BiLSTM Confusion Matrix"""

# ============================================
# BLOCK 67 — BiLSTM Confusion Matrix
# ============================================

cm_bilstm = confusion_matrix(
    y_test_nn,
    bilstm_predictions
)

plt.figure(figsize=(7, 6))

sns.heatmap(
    cm_bilstm,
    annot=True,
    fmt="d",
    cmap="Purples",
    xticklabels=[
        "Phishing",
        "Legitimate"
    ],
    yticklabels=[
        "Phishing",
        "Legitimate"
    ]
)

plt.title("Character-Level BiLSTM Confusion Matrix")
plt.xlabel("Predicted Label")
plt.ylabel("Actual Label")

plt.show()

"""#Compare CNN and BiLSTM"""

# ============================================
# BLOCK 68 — Compare CNN vs BiLSTM
# ============================================

model_comparison = pd.DataFrame({
    "Model": [
        "Character CNN",
        "Character BiLSTM"
    ],

    "Accuracy": [
        cnn_accuracy,
        bilstm_accuracy
    ],

    "Precision": [
        cnn_precision,
        bilstm_precision
    ],

    "Recall": [
        cnn_recall,
        bilstm_recall
    ],

    "F1 Score": [
        cnn_f1,
        bilstm_f1
    ],

    "ROC-AUC": [
        cnn_auc,
        bilstm_auc
    ]
})

display(
    model_comparison.style.format({
        "Accuracy": "{:.4f}",
        "Precision": "{:.4f}",
        "Recall": "{:.4f}",
        "F1 Score": "{:.4f}",
        "ROC-AUC": "{:.4f}"
    })
)

"""#Visualize CNN vs BiLSTM Performance"""

# ============================================
# BLOCK 69 — Visualize Model Comparison
# ============================================

comparison_plot = model_comparison.set_index("Model")

comparison_plot[
    ["Accuracy", "Precision", "Recall", "F1 Score", "ROC-AUC"]
].plot(
    kind="bar",
    figsize=(11, 6)
)

plt.title("Character CNN vs Character BiLSTM")
plt.xlabel("Model")
plt.ylabel("Score")
plt.ylim(0, 1.05)
plt.xticks(rotation=0)
plt.legend(loc="lower right")
plt.grid(axis="y")

plt.show()

"""#Save BiLSTM Model"""

# ============================================
# BLOCK 70 — Save Character-Level BiLSTM
# ============================================

bilstm_model.save(
    "phishshield_url_bilstm.keras"
)

print("BiLSTM model saved successfully.")

"""#Prepare HTML Feature Extraction Libraries"""

# HTML Feature Extraction Libraries

!pip -q install beautifulsoup4 lxml

from bs4 import BeautifulSoup
import re
import numpy as np
import pandas as pd

print("HTML libraries are ready.")

"""#Identify HTML/Website Features"""

# Identify HTML / Website-related features

html_keywords = [
    "html", "title", "favicon", "robot", "responsive",
    "redirect", "description", "popup", "iframe",
    "form", "social", "submit", "hidden", "password",
    "bank", "pay", "crypto", "copyright",
    "image", "css", "js", "selfref", "emptyref", "externalref",
    "lineofcode", "largestline"
]

html_feature_candidates = [
    col for col in data.columns
    if any(keyword in col.lower().replace("_", "")
           for keyword in html_keywords)
]

print("HTML / Website-related features:")
for col in html_feature_candidates:
    print("-", col)

print("\nTotal:", len(html_feature_candidates))

"""#Remove Text-only and URL-overlap Features"""

# Keep mainly structural HTML / website features
# Remove text-heavy and URL-overlap features

exclude_features = [
    "Title",
    "DomainTitleMatchScore",
    "URLTitleMatchScore"
]

html_features = [
    col for col in html_feature_candidates
    if col not in exclude_features
]

print("Selected HTML / Website features:")
for col in html_features:
    print("-", col)

print("\nTotal selected features:", len(html_features))

"""#Create HTML Dataset"""

# Create HTML / Website feature dataset

html_data = data[html_features + ["label"]].copy()

print("HTML dataset shape:", html_data.shape)

display(html_data.head())

"""#Check Missing Values"""

# Check missing values

missing_html = html_data.isnull().sum()

print("Total missing values:",
      missing_html.sum())

display(
    missing_html[missing_html > 0]
    .sort_values(ascending=False)
)

"""#Convert Features to Numeric"""

# Convert HTML / Website features to numeric values

for col in html_features:
    html_data[col] = pd.to_numeric(
        html_data[col],
        errors="coerce"
    )

html_data[html_features] = html_data[html_features].fillna(0)

print("All HTML features converted to numeric format.")
print("Remaining missing values:",
      html_data[html_features].isnull().sum().sum())

"""#Prepare X and y"""

# Prepare HTML feature matrix and labels

X_html = html_data[html_features].values.astype("float32")
y_html = html_data["label"].values.astype("float32")

print("HTML Feature Matrix:", X_html.shape)
print("Labels:", y_html.shape)

"""#Prepare X and y"""

# Prepare HTML feature matrix and labels

X_html = html_data[html_features].values.astype("float32")
y_html = html_data["label"].values.astype("float32")

print("HTML Feature Matrix:", X_html.shape)
print("Labels:", y_html.shape)

"""#Train/Validation/Test Split"""

from sklearn.model_selection import train_test_split

# 80% Train, 10% Validation, 10% Test

X_html_train, X_html_temp, y_html_train, y_html_temp = train_test_split(
    X_html,
    y_html,
    test_size=0.20,
    stratify=y_html,
    random_state=42
)

X_html_val, X_html_test, y_html_val, y_html_test = train_test_split(
    X_html_temp,
    y_html_temp,
    test_size=0.50,
    stratify=y_html_temp,
    random_state=42
)

print("Train:", X_html_train.shape)
print("Validation:", X_html_val.shape)
print("Test:", X_html_test.shape)

"""#Standardize HTML Features"""

from sklearn.preprocessing import StandardScaler

# Fit scaler ONLY on training data

html_scaler = StandardScaler()

X_html_train_scaled = html_scaler.fit_transform(X_html_train)
X_html_val_scaled = html_scaler.transform(X_html_val)
X_html_test_scaled = html_scaler.transform(X_html_test)

print("HTML features standardized successfully.")

"""#Verify HTML Split"""

# Verify class distribution

print("Training distribution:")
print(pd.Series(y_html_train).value_counts().sort_index())

print("\nValidation distribution:")
print(pd.Series(y_html_val).value_counts().sort_index())

print("\nTest distribution:")
print(pd.Series(y_html_test).value_counts().sort_index())

"""#Build HTML Neural Network"""

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, BatchNormalization

html_model = Sequential([
    Dense(128, activation="relu",
          input_shape=(X_html_train_scaled.shape[1],)),

    BatchNormalization(),
    Dropout(0.30),

    Dense(64, activation="relu"),
    Dropout(0.30),

    Dense(32, activation="relu"),
    Dropout(0.20),

    Dense(1, activation="sigmoid")
])

html_model.summary()

"""#Compile HTML Neural Network"""

from tensorflow.keras.optimizers import Adam

html_model.compile(
    optimizer=Adam(learning_rate=0.001),
    loss="binary_crossentropy",
    metrics=[
        "accuracy",
        tf.keras.metrics.Precision(name="precision"),
        tf.keras.metrics.Recall(name="recall")
    ]
)

print("HTML Neural Network compiled successfully.")

"""#HTML Model Callbacks"""

from tensorflow.keras.callbacks import (
    EarlyStopping,
    ReduceLROnPlateau,
    ModelCheckpoint
)

html_callbacks = [

    EarlyStopping(
        monitor="val_loss",
        patience=4,
        restore_best_weights=True
    ),

    ReduceLROnPlateau(
        monitor="val_loss",
        factor=0.5,
        patience=2,
        min_lr=1e-6
    ),

    ModelCheckpoint(
        "best_html_model.keras",
        monitor="val_loss",
        save_best_only=True
    )
]

print("HTML callbacks are ready.")

"""#Train HTML Neural Network"""

# Train HTML / Website Neural Network

html_history = html_model.fit(
    X_html_train_scaled,
    y_html_train,

    validation_data=(
        X_html_val_scaled,
        y_html_val
    ),

    epochs=20,
    batch_size=256,
    callbacks=html_callbacks,
    verbose=1
)

"""#Evaluate HTML Model"""

# Evaluate HTML model on test data

html_test_results = html_model.evaluate(
    X_html_test_scaled,
    y_html_test,
    verbose=0
)

for name, value in zip(
    html_model.metrics_names,
    html_test_results
):
    print(f"{name}: {value:.4f}")

"""#HTML Training Accuracy"""

plt.figure(figsize=(8, 5))

plt.plot(
    html_history.history["accuracy"],
    label="Training Accuracy"
)

plt.plot(
    html_history.history["val_accuracy"],
    label="Validation Accuracy"
)

plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.title("HTML Neural Network - Accuracy")

plt.legend()
plt.grid(True)
plt.show()

"""#HTML Training Loss"""

plt.figure(figsize=(8, 5))

plt.plot(
    html_history.history["loss"],
    label="Training Loss"
)

plt.plot(
    html_history.history["val_loss"],
    label="Validation Loss"
)

plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("HTML Neural Network - Loss")

plt.legend()
plt.grid(True)
plt.show()

"""#HTML Predictions"""

# Generate phishing probabilities

html_probabilities = html_model.predict(
    X_html_test_scaled,
    verbose=0
).ravel()

# Convert probabilities into class predictions

html_predictions = (
    html_probabilities >= 0.50
).astype(int)

print("Prediction completed.")

print("\nFirst 10 probabilities:")
print(html_probabilities[:10])

print("\nFirst 10 predictions:")
print(html_predictions[:10])

"""#HTML Detailed Metrics"""

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    classification_report
)

html_accuracy = accuracy_score(
    y_html_test,
    html_predictions
)

html_precision = precision_score(
    y_html_test,
    html_predictions
)

html_recall = recall_score(
    y_html_test,
    html_predictions
)

html_f1 = f1_score(
    y_html_test,
    html_predictions
)

html_roc_auc = roc_auc_score(
    y_html_test,
    html_probabilities
)

print("HTML / Website Neural Network Results")
print("--------------------------------------")
print(f"Accuracy : {html_accuracy:.4f}")
print(f"Precision: {html_precision:.4f}")
print(f"Recall   : {html_recall:.4f}")
print(f"F1 Score : {html_f1:.4f}")
print(f"ROC-AUC  : {html_roc_auc:.4f}")

print("\nClassification Report:")
print(
    classification_report(
        y_html_test,
        html_predictions,
        target_names=["Phishing", "Legitimate"]
    )
)

"""#HTML Confusion Matrix"""

from sklearn.metrics import confusion_matrix

html_cm = confusion_matrix(
    y_html_test,
    html_predictions
)

plt.figure(figsize=(6, 5))

sns.heatmap(
    html_cm,
    annot=True,
    fmt="d",
    cmap="Blues",
    xticklabels=["Phishing", "Legitimate"],
    yticklabels=["Phishing", "Legitimate"]
)

plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("HTML Neural Network - Confusion Matrix")

plt.show()

"""#Save HTML Model and Scaler"""

import joblib

# Save trained HTML model
html_model.save("phishshield_html_nn.keras")

# Save scaler
joblib.dump(
    html_scaler,
    "phishshield_html_scaler.pkl"
)

# Save feature names
joblib.dump(
    html_features,
    "phishshield_html_features.pkl"
)

print("HTML model saved successfully.")
print("Scaler saved successfully.")
print("Feature list saved successfully.")

"""#

#Create HTML Model Result Summary
"""

html_result = pd.DataFrame({
    "Model": ["HTML Neural Network"],
    "Accuracy": [html_accuracy],
    "Precision": [html_precision],
    "Recall": [html_recall],
    "F1 Score": [html_f1],
    "ROC-AUC": [html_roc_auc]
})

display(html_result)

"""#Compare URL Models with HTML Model"""

# Use the previously calculated URL model metrics
# from Block 68

final_model_comparison = pd.DataFrame({
    "Model": [
        "Character CNN",
        "BiLSTM",
        "HTML Neural Network"
    ],

    "Accuracy": [
        cnn_accuracy,
        bilstm_accuracy,
        html_accuracy
    ],

    "Precision": [
        cnn_precision,
        bilstm_precision,
        html_precision
    ],

    "Recall": [
        cnn_recall,
        bilstm_recall,
        html_recall
    ],

    "F1 Score": [
        cnn_f1,
        bilstm_f1,
        html_f1
    ],

    "ROC-AUC": [
        cnn_roc_auc,
        bilstm_roc_auc,
        html_roc_auc
    ]
})

display(final_model_comparison)

"""#Visualize Model Comparison"""

plt.figure(figsize=(10, 6))

x = np.arange(len(final_model_comparison["Model"]))
width = 0.18

plt.bar(
    x - 2*width,
    final_model_comparison["Accuracy"],
    width,
    label="Accuracy"
)

plt.bar(
    x - width,
    final_model_comparison["Precision"],
    width,
    label="Precision"
)

plt.bar(
    x,
    final_model_comparison["Recall"],
    width,
    label="Recall"
)

plt.bar(
    x + width,
    final_model_comparison["F1 Score"],
    width,
    label="F1 Score"
)

plt.bar(
    x + 2*width,
    final_model_comparison["ROC-AUC"],
    width,
    label="ROC-AUC"
)

plt.xticks(
    x,
    final_model_comparison["Model"]
)

plt.ylabel("Score")
plt.title("URL and HTML Model Comparison")

plt.ylim(0, 1.05)
plt.legend()
plt.grid(axis="y")

plt.show()

"""#Save Model Comparison"""

# Save comparison results

final_model_comparison.to_csv(
    "phishshield_model_comparison.csv",
    index=False
)

print("Model comparison saved successfully.")

"""#Save HTML Branch Artifacts

#
"""

# Save important HTML branch information

html_branch_info = {
    "features": html_features,
    "number_of_features": len(html_features),
    "model": "HTML Neural Network",
    "accuracy": html_accuracy,
    "precision": html_precision,
    "recall": html_recall,
    "f1_score": html_f1,
    "roc_auc": html_roc_auc
}

joblib.dump(
    html_branch_info,
    "phishshield_html_branch_info.pkl"
)

print("HTML branch information saved successfully.")

"""#Final HTML Branch Summary"""

print("=" * 55)
print("PHISHSHIELD AI - HTML / WEBSITE BRANCH")
print("=" * 55)

print(f"Number of Features : {len(html_features)}")
print(f"Test Accuracy      : {html_accuracy:.4f}")
print(f"Precision          : {html_precision:.4f}")
print(f"Recall             : {html_recall:.4f}")
print(f"F1 Score           : {html_f1:.4f}")
print(f"ROC-AUC            : {html_roc_auc:.4f}")

print("\nHTML Branch Status: COMPLETE")
print("=" * 55)

"""#Install Screenshot/Image Libraries"""

# Screenshot / Image Branch

!pip -q install datasets huggingface_hub pillow

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from PIL import Image

print("Screenshot/Image libraries are ready.")

"""#Download Screenshot Dataset Metadata"""

from huggingface_hub import hf_hub_download

# Download metadata from the screenshot dataset
metadata_path = hf_hub_download(
    repo_id="shresthsamyak/phishing-website-screenshots",
    filename="metadata.csv",
    repo_type="dataset"
)

print("Metadata downloaded:")
print(metadata_path)

"""#Load Screenshot Metadata"""

screenshot_df = pd.read_csv(metadata_path)

print("Dataset shape:", screenshot_df.shape)

display(screenshot_df.head())

print("\nColumns:")
print(screenshot_df.columns.tolist())

"""#Check Screenshot Class Distribution"""

print("Screenshot class distribution:")
display(
    screenshot_df["label"]
    .value_counts()
    .sort_index()
)

print("\nLabel meaning:")
print("0 = Legitimate")
print("1 = Phishing")

"""#Dataset Quality Check"""

print("Missing values:")
display(
    screenshot_df.isnull().sum()
    .sort_values(ascending=False)
    .head(15)
)

print("\nDuplicate rows:",
      screenshot_df.duplicated().sum())

print("\nBlank images:",
      screenshot_df["is_blank"].sum()
      if "is_blank" in screenshot_df.columns
      else "Column not available")

"""#Create Balanced Image Dataset"""

# Balance the classes for a fair visual model experiment

legitimate_df = screenshot_df[
    screenshot_df["label"] == 0
]

phishing_df = screenshot_df[
    screenshot_df["label"] == 1
]

# Use all phishing samples and the same number of legitimate samples
n_samples = min(
    len(legitimate_df),
    len(phishing_df)
)

legitimate_sample = legitimate_df.sample(
    n=n_samples,
    random_state=42
)

phishing_sample = phishing_df.sample(
    n=n_samples,
    random_state=42
)

balanced_screenshot_df = pd.concat(
    [
        legitimate_sample,
        phishing_sample
    ],
    ignore_index=True
)

balanced_screenshot_df = balanced_screenshot_df.sample(
    frac=1,
    random_state=42
).reset_index(drop=True)

print("Balanced dataset shape:",
      balanced_screenshot_df.shape)

print("\nClass distribution:")
display(
    balanced_screenshot_df["label"]
    .value_counts()
    .sort_index()
)

"""#Inspect Screenshot Paths"""

print("Example screenshot paths:")

display(
    balanced_screenshot_df[
        ["file_name", "label"]
    ].head(10)
)

"""#Download Image Dataset Files"""

from datasets import load_dataset

# Load the image dataset
image_dataset = load_dataset(
    "shresthsamyak/phishing-website-screenshots"
)

print(image_dataset)

"""#Inspect Available Image Samples"""

# Inspect the first few samples

sample = image_dataset["train"][0]

print("Available fields:")
print(sample.keys())

print("\nLabel:", sample["label"])

if "image" in sample:
    print("Image size:", sample["image"].size)

"""#Display Sample Screenshots"""

fig, axes = plt.subplots(
    2, 4,
    figsize=(16, 8)
)

for i, ax in enumerate(axes.flat):

    sample = image_dataset["train"][i]

    ax.imshow(sample["image"])
    ax.set_title(
        "Phishing"
        if sample["label"] == 1
        else "Legitimate"
    )
    ax.axis("off")

plt.tight_layout()
plt.show()

"""#Define Image Size"""

# Standard input size for CNN

IMG_HEIGHT = 224
IMG_WIDTH = 224
CHANNELS = 3

print("Image size:",
      IMG_HEIGHT,
      "x",
      IMG_WIDTH)

print("Channels:", CHANNELS)

"""#Prepare Image Arrays"""

from PIL import Image

X_images = []
y_images = []

for sample in image_dataset["train"]:

    image = sample["image"].convert("RGB")

    image = image.resize(
        (IMG_WIDTH, IMG_HEIGHT)
    )

    image_array = np.array(image)

    X_images.append(image_array)
    y_images.append(sample["label"])

X_images = np.array(
    X_images,
    dtype=np.float32
)

y_images = np.array(
    y_images,
    dtype=np.int32
)

print("Image data shape:",
      X_images.shape)

print("Label shape:",
      y_images.shape)

"""#Normalize Images"""

# Normalize pixel values from 0-255 to 0-1

X_images = X_images / 255.0

print("Minimum pixel value:",
      X_images.min())

print("Maximum pixel value:",
      X_images.max())

"""#Stratified Image Split"""

from sklearn.model_selection import train_test_split

X_img_train, X_img_temp, y_img_train, y_img_temp = train_test_split(
    X_images,
    y_images,
    test_size=0.20,
    stratify=y_images,
    random_state=42
)

X_img_val, X_img_test, y_img_val, y_img_test = train_test_split(
    X_img_temp,
    y_img_temp,
    test_size=0.50,
    stratify=y_img_temp,
    random_state=42
)

print("Training:", X_img_train.shape)
print("Validation:", X_img_val.shape)
print("Testing:", X_img_test.shape)

"""#Verify Image Classes"""

print("Training classes:")
print(pd.Series(y_img_train).value_counts().sort_index())

print("\nValidation classes:")
print(pd.Series(y_img_val).value_counts().sort_index())

print("\nTest classes:")
print(pd.Series(y_img_test).value_counts().sort_index())

"""#Calculate Class Weights"""

from sklearn.utils.class_weight import compute_class_weight

classes = np.unique(y_img_train)

weights = compute_class_weight(
    class_weight="balanced",
    classes=classes,
    y=y_img_train
)

image_class_weights = dict(
    zip(classes, weights)
)

print("Image class weights:")
print(image_class_weights)

"""#Build Screenshot CNN"""

import tensorflow as tf

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import (
    Conv2D,
    MaxPooling2D,
    BatchNormalization,
    GlobalAveragePooling2D,
    Dense,
    Dropout
)

image_cnn = Sequential([

    Conv2D(
        32,
        (3, 3),
        activation="relu",
        input_shape=(
            IMG_HEIGHT,
            IMG_WIDTH,
            CHANNELS
        )
    ),

    BatchNormalization(),
    MaxPooling2D((2, 2)),

    Conv2D(
        64,
        (3, 3),
        activation="relu"
    ),

    BatchNormalization(),
    MaxPooling2D((2, 2)),

    Conv2D(
        128,
        (3, 3),
        activation="relu"
    ),

    BatchNormalization(),
    MaxPooling2D((2, 2)),

    Conv2D(
        256,
        (3, 3),
        activation="relu"
    ),

    BatchNormalization(),

    GlobalAveragePooling2D(),

    Dense(
        128,
        activation="relu"
    ),

    Dropout(0.40),

    Dense(
        1,
        activation="sigmoid"
    )
])

image_cnn.summary()

"""#Compile Screenshot CNN"""

image_cnn.compile(
    optimizer=tf.keras.optimizers.Adam(
        learning_rate=0.001
    ),

    loss="binary_crossentropy",

    metrics=[
        "accuracy",
        tf.keras.metrics.Precision(
            name="precision"
        ),
        tf.keras.metrics.Recall(
            name="recall"
        )
    ]
)

print("Screenshot CNN compiled successfully.")

"""#Image Model Callbacks"""

from tensorflow.keras.callbacks import (
    EarlyStopping,
    ReduceLROnPlateau,
    ModelCheckpoint
)

image_callbacks = [

    EarlyStopping(
        monitor="val_loss",
        patience=4,
        restore_best_weights=True
    ),

    ReduceLROnPlateau(
        monitor="val_loss",
        factor=0.5,
        patience=2,
        min_lr=1e-6
    ),

    ModelCheckpoint(
        "best_screenshot_cnn.keras",
        monitor="val_loss",
        save_best_only=True
    )
]

print("Image callbacks are ready.")

"""#Train Screenshot CNN"""

image_history = image_cnn.fit(
    X_img_train,
    y_img_train,

    validation_data=(
        X_img_val,
        y_img_val
    ),

    epochs=20,
    batch_size=32,

    class_weight=image_class_weights,

    callbacks=image_callbacks,

    verbose=1
)

"""#Evaluate Screenshot CNN"""

image_test_results = image_cnn.evaluate(
    X_img_test,
    y_img_test,
    verbose=0
)

for name, value in zip(
    image_cnn.metrics_names,
    image_test_results
):
    print(f"{name}: {value:.4f}")

"""#Screenshot Accuracy Graph"""

plt.figure(figsize=(8, 5))

plt.plot(
    image_history.history["accuracy"],
    label="Training Accuracy"
)

plt.plot(
    image_history.history["val_accuracy"],
    label="Validation Accuracy"
)

plt.xlabel("Epoch")
plt.ylabel("Accuracy")

plt.title(
    "Screenshot CNN - Accuracy"
)

plt.legend()
plt.grid(True)

plt.show()

"""#Screenshot Loss Graph"""

plt.figure(figsize=(8, 5))

plt.plot(
    image_history.history["loss"],
    label="Training Loss"
)

plt.plot(
    image_history.history["val_loss"],
    label="Validation Loss"
)

plt.xlabel("Epoch")
plt.ylabel("Loss")

plt.title(
    "Screenshot CNN - Loss"
)

plt.legend()
plt.grid(True)

plt.show()

"""#Screenshot Predictions"""

image_probabilities = image_cnn.predict(
    X_img_test,
    verbose=0
).ravel()

image_predictions = (
    image_probabilities >= 0.50
).astype(int)

print("Screenshot prediction completed.")

print("\nFirst 10 probabilities:")
print(image_probabilities[:10])

print("\nFirst 10 predictions:")
print(image_predictions[:10])

"""#Screenshot Detailed Metrics"""

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    classification_report
)

image_accuracy = accuracy_score(
    y_img_test,
    image_predictions
)

image_precision = precision_score(
    y_img_test,
    image_predictions
)

image_recall = recall_score(
    y_img_test,
    image_predictions
)

image_f1 = f1_score(
    y_img_test,
    image_predictions
)

image_roc_auc = roc_auc_score(
    y_img_test,
    image_probabilities
)

print("SCREENSHOT CNN RESULTS")
print("=======================")

print(f"Accuracy : {image_accuracy:.4f}")
print(f"Precision: {image_precision:.4f}")
print(f"Recall   : {image_recall:.4f}")
print(f"F1 Score : {image_f1:.4f}")
print(f"ROC-AUC  : {image_roc_auc:.4f}")

print("\nClassification Report:")

print(
    classification_report(
        y_img_test,
        image_predictions,
        target_names=[
            "Legitimate",
            "Phishing"
        ]
    )
)

"""#Screenshot Confusion Matrix"""

from sklearn.metrics import confusion_matrix

image_cm = confusion_matrix(
    y_img_test,
    image_predictions
)

plt.figure(figsize=(6, 5))

sns.heatmap(
    image_cm,
    annot=True,
    fmt="d",
    cmap="Blues",

    xticklabels=[
        "Legitimate",
        "Phishing"
    ],

    yticklabels=[
        "Legitimate",
        "Phishing"
    ]
)

plt.xlabel("Predicted")
plt.ylabel("Actual")

plt.title(
    "Screenshot CNN - Confusion Matrix"
)

plt.show()

"""#Save Screenshot Model"""

import joblib

image_cnn.save(
    "phishshield_screenshot_cnn.keras"
)

joblib.dump(
    {
        "image_height": IMG_HEIGHT,
        "image_width": IMG_WIDTH,
        "channels": CHANNELS,
        "threshold": 0.50
    },
    "phishshield_screenshot_config.pkl"
)

print("Screenshot CNN saved successfully.")

"""#Screenshot Branch Summary"""

print("=" * 55)
print("PHISHSHIELD AI - SCREENSHOT / VISUAL BRANCH")
print("=" * 55)

print(f"Image Size    : {IMG_HEIGHT} x {IMG_WIDTH}")
print(f"Model         : CNN")
print(f"Test Accuracy : {image_accuracy:.4f}")
print(f"Precision     : {image_precision:.4f}")
print(f"Recall        : {image_recall:.4f}")
print(f"F1 Score      : {image_f1:.4f}")
print(f"ROC-AUC       : {image_roc_auc:.4f}")

print("\nScreenshot Branch Status: COMPLETE")
print("=" * 55)

"""Check Whether Screenshot Data Can Be Paired with URL/HTML Data"""

# Check whether the screenshot dataset contains
# URL/domain information that can be matched
# with our PhiUSIIL URL + HTML data.

print("Screenshot dataset columns:")
print(screenshot_df.columns.tolist())

print("\n----------------------------------")

print("Possible URL/domain columns:")

possible_pair_columns = [
    col for col in screenshot_df.columns
    if any(
        key in col.lower()
        for key in [
            "url",
            "domain",
            "website",
            "link",
            "address",
            "host"
        ]
    )
]

if possible_pair_columns:
    for col in possible_pair_columns:
        print("-", col)
else:
    print("No URL/domain pairing column found.")